FROM nginx

CMD ["/start"]
ENV API_URL=http://localhost:3000

RUN rm -rf /usr/share/nginx/html

COPY start /
COPY default.conf /etc/nginx/conf.d/default.conf

COPY index.html.template /
COPY www /usr/share/nginx/html
